---
title: "{{< meta tagline >}}"
---

{{< include /docs/includes/_badges.qmd >}}

This is a template for creating a new repository for research data as a FAIR and
structured data package. Use this template to quickly get started with creating
and effectively developing a data package, that has the organisation and
configuration files to make developing and building data packages easier.

## Features

- Use [uv](https://decisions.seedcase-project.org/why-uv/) to manage the Data
  Package.
- Use [Polars](https://www.pola.rs/) for data manipulation.
- Use [Seedcase Sprout](https://sprout.seedcase-project.org/) to create and
  modify the data package.
- Use [Seedcase Flower](https://flower.seedcase-project.org/) to generate a
  website for the data package.
- Build management with [justfile](https://just.systems/man/en/).
- Check typos with [typos](https://github.com/crate-ci/typos).
- Code formatting and linting with
  [ruff](https://decisions.seedcase-project.org/why-ruff/).
- Pre-commit hooks with [pre-commit](https://pre-commit.com/).
- GitHub workflows for automatically adding Pull Requests and Issues to a
  project board.
- Pull Request template for easy creation of new Pull Requests.
- [VS Code](https://code.visualstudio.com/) settings commonly used by
  contributors working in VS Code.
- [EditorConfig](https://editorconfig.org/) for common cross-editor settings for
  contributors.
- [`CITATION.cff`](https://citation-file-format.github.io/) file for citation
  information.
- Website generation with [Quarto](https://quarto.org/).
- Folder and file structure that mimics a Python package to take advantage of
  Python's packaging ecosystem.
- [`pyproject.toml`](https://peps.python.org/pep-0518/) for tracking
  dependencies and project metadata.
- Use [MIT License](https://decisions.seedcase-project.org/why-mit-license/) for
  the code used in the data package made from this template.
- Optionally use the [CC0
  License](https://decisions.seedcase-project.org/why-cc0-data/) for the data in
  the data package made from this template.

## Want to contribute?

We would love your feedback or contributions! Head over to our [GitHub
repository]({{< meta links.github >}}) to share your ideas or contribute code.
Your input makes us better!

### Contributors

{{< include /docs/includes/_contributors.qmd >}}

## Licensing

This project is licensed under the [MIT License](/LICENSE.md).
