import seedcase_sprout as sp

# from .resource_properties import resource_properties

properties = sp.PackageProperties(
    ## Required:
    name="template-data-package",
    title="",
    description="",
    licenses=[
        sp.LicenseProperties(
            ## Required:
            name="",
            ## Optional:
            # path="",
            # title="",
        ),
    ],
    ## Optional:
    # homepage="",
    # contributors=[
    #    sp.ContributorProperties(
    #        ## Required:
    #        title="",
    #        ## Optional:
    #        path="",
    #        email="",
    #        given_name="",
    #        family_name="",
    #        organization="",
    #        roles=[""],
    #    ),
    # ],
    # keywords=[""],
    # image="",
    # sources=[
    #    sp.SourceProperties(
    #        ## Required:
    #        title="",
    #        ## Optional:
    #        path="",
    #        email="",
    #        version="",
    #    ),
    # ],
    # resources=[
    #     resource_properties,
    # ],
    ## Autogenerated:
    id="108e33ad-33f9-414f-a93c-bfed390be4e6",
    version="0.1.0",
    created="2025-07-04T15:17:28+01:00",
)