name: Test template creation

on:
  push:
    branches:
      - main
  pull_request:

# Least privilege permissions
permissions: read-all

jobs:
  test-copier:
    runs-on: ubuntu-latest
    env:
      TEMPLATE_NAME: template-data-package
      TEST_PACKAGE: test-data-package
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          # Clone template to a subdirectory
          path: ${{ env.TEMPLATE_NAME }}

      - name: Set up uv
        uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba
        with:
          enable-cache: true
          cache-dependency-glob: "**/uv.lock"

      - name: Install justfile
        run: sudo apt-get install -y just

      - name: Test and check template creation
        run: just test
